

const CompagnieCarrier = () =>{
    const dict3 = {
        'AA': 'American Airlines',
        'AF': 'Air France',
        'AI': 'Air India',
        'BA': 'British Airways',
        'CA': 'Air China',
        'CX': 'Cathay Pacific',
        'DL': 'Delta Air Lines',
        'EK': 'Emirates',
        'EY': 'Etihad Airways',
        'GA': 'Garuda Indonesia',
        'JL': 'Japan Airlines',
        'KL': 'KLM Royal Dutch Airlines',
        'LH': 'Lufthansa',
        'LX': 'Swiss International Air Lines',
        'MH': 'Malaysia Airlines',
        'NZ': 'Air New Zealand',
        'QF': 'Qantas',
        'QR': 'Qatar Airways',
        'SA': 'South African Airways',
        'SQ': 'Singapore Airlines',
        'SU': 'Aeroflot',
        'TK': 'Turkish Airlines',
        'UA': 'United Airlines',
        'VA': 'Virgin Australia',
        'VN': 'Vietnam Airlines',
        'VS': 'Virgin Atlantic',
        'WS': 'WestJet',
        'WN': 'Southwest Airlines',
        'AC': 'Air Canada',
        'AZ': 'Alitalia',
        'SK': 'Scandinavian Airlines',
        'IB': 'Iberia',
        'TP': 'TAP Portugal',
        'OS': 'Austrian Airlines',
        'AY': 'Finnair',
        'SN': 'Brussels Airlines',
        'LO': 'LOT Polish Airlines',
        'OK': 'Czech Airlines',
        'RO': 'TAROM',
        'HU': 'Hainan Airlines',
        'MU': 'China Eastern Airlines',
        'CZ': 'China Southern Airlines',
        'MF': 'XiamenAir',
        'BR': 'EVA Air',
        'CI': 'China Airlines',
        'TG': 'Thai Airways',
        'PG': 'Bangkok Airways',
        'UL': 'SriLankan Airlines',
        'G8': 'GoAir',
        '6E': 'IndiGo',
        'UK': 'Vistara',
        'I5': 'AirAsia India',
        'SG': 'SpiceJet',
        '9W': 'Jet Airways',
        'FZ': 'Flydubai',
        'G9': 'Air Arabia',
        'RJ': 'Royal Jordanian',
        'MS': 'EgyptAir',
        'ET': 'Ethiopian Airlines',
        'KQ': 'Kenya Airways',
        'AT': 'Royal Air Maroc',
        'TN': 'Air Tahiti Nui',
        'FJ': 'Fiji Airways',
        'HA': 'Hawaiian Airlines',
        'NH': 'All Nippon Airways',
        'KE': 'Korean Air',
        'OZ': 'Asiana Airlines',
        'PR': 'Philippine Airlines',
        'Z2': 'Philippines AirAsia',
        'TR': 'Scoot',
        'MI': 'SilkAir',
        'TZ': 'Scoot',
        'FD': 'Thai AirAsia',
        'SL': 'Thai Lion Air',
        'VJ': 'VietJet Air',
        'SV': 'Saudia',
        'KU': 'Kuwait Airways',
        'WY': 'Oman Air',
        'GF': 'Gulf Air',
        'ME': 'Middle East Airlines',
    };

    const compagnieVol = {};
    for (const key in dict3){
        compagnieVol[key] = dict3[key]
    }
    return  compagnieVol;
}

export default CompagnieCarrier;